name: AuroraMusic
options:
  bundleIdPrefix: com.aurora
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ENABLE_USER_SCRIPT_SANDBOXING: YES
targets:
  AuroraMusic:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - sdk: JavaScriptCore.framework
      - sdk: AVFoundation.framework
      - sdk: MediaPlayer.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.aurora.music
        INFOPLIST_FILE: Sources/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_EMIT_LOC_STRINGS: YES
